language: node_js
node_js:
  - "8.12"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install --global gatsby-cli

script:
  - gatsby build

after_success:
  - firebase deploy --token=${FIREBASE_API_TOKEN}